import React from "react";
import "./cvTemplates.css";

interface ExperienceItem {
  title?: string;
  company?: string;
  city?: string;
  startEnd?: string;
  duration?: string;
  bullets?: string[];
  description?: string;
}

interface EducationItem {
  degree?: string;
  school?: string;
  year?: string;
}

interface CVData {
  fullName?: string;
  city?: string;
  location?: string;
  phone?: string;
  email?: string;
  links?: string[];
  summary?: string;
  jobTitle?: string;
  experience?: ExperienceItem[];
  enhancedExperience?: ExperienceItem[];
  education?: EducationItem[];
  enhancedEducation?: EducationItem[];
  skills?: string[];
  enhancedSkills?: string[];
  certs?: string[];
}

interface CVRenderProps {
  data: CVData;
  templateId?: string;
  watermark?: boolean;
}

export default function CVRender({ data, templateId, watermark = false }: CVRenderProps) {
  const tpl = templateId || "ats_ar_classic";
  const isAr = tpl.startsWith("ats_ar");
  const dir = isAr ? "rtl" : "ltr";
  const lang = isAr ? "ar" : "en";

  const experience = data.enhancedExperience || data.experience || [];
  const education = data.enhancedEducation || data.education || [];
  const skills = data.enhancedSkills || data.skills || defaultSkills(isAr);
  const certs = data.certs || defaultCerts(isAr);

  return (
    <div className="cv-page" dir={dir} lang={lang} data-template={tpl} style={{ position: 'relative' }}>
      {watermark && (
        <div style={{
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%) rotate(-35deg)',
          fontSize: '48px',
          fontWeight: 900,
          color: 'rgba(0,0,0,0.06)',
          whiteSpace: 'nowrap',
          pointerEvents: 'none',
          zIndex: 10,
          userSelect: 'none',
        }}>
          Generated by Sira AI
        </div>
      )}

      <Header data={data} isAr={isAr} />

      <Section title={isAr ? "الملخص المهني" : "Professional Summary"}>
        <p className="cv-text">{data.summary || (isAr ? "اكتب ملخصًا مهنيًا من 3–4 أسطر." : "Write a 3–4 line summary.")}</p>
      </Section>

      <Section title={isAr ? "الخبرة العملية" : "Work Experience"}>
        {experience.length ? (
          experience.map((job: ExperienceItem, idx: number) => (
            <div key={idx} className="cv-item">
              <div className="cv-item-head">
                <div className="cv-item-title">{job.title || (isAr ? "المسمى الوظيفي" : "Job Title")}</div>
                <div className="cv-item-meta">
                  {joinMeta([job.company, job.city, job.startEnd || job.duration], " • ")}
                </div>
              </div>
              <ul className="cv-bullets">
                {(job.bullets || (job.description ? [job.description] : [])).slice(0, 6).map((b: string, bi: number) => (
                  <li key={bi}>{b}</li>
                ))}
              </ul>
            </div>
          ))
        ) : (
          <p className="cv-text">{isAr ? "أضف خبراتك هنا (بنقاط إنجاز)." : "Add your experience here (bullet achievements)."}</p>
        )}
      </Section>

      <TwoColBlock templateId={tpl}>
        <Section title={isAr ? "التعليم" : "Education"}>
          {education.length ? (
            education.map((e: EducationItem, idx: number) => (
              <div key={idx} className="cv-item">
                <div className="cv-item-title">{e.degree || (isAr ? "الدرجة والتخصص" : "Degree")}</div>
                <div className="cv-item-meta">
                  {joinMeta([e.school, e.year], " • ")}
                </div>
              </div>
            ))
          ) : (
            <p className="cv-text">{isAr ? "أضف مؤهلك العلمي." : "Add your education."}</p>
          )}
        </Section>

        <Section title={isAr ? "المهارات" : "Skills"}>
          <ul className="cv-skills">
            {skills.slice(0, 18).map((s: string, idx: number) => (
              <li key={idx}>{s}</li>
            ))}
          </ul>
        </Section>
      </TwoColBlock>

      {certs.length > 0 && (
        <Section title={isAr ? "الدورات والشهادات" : "Courses & Certifications"}>
          <ul className="cv-bullets">
            {certs.slice(0, 10).map((c: string, idx: number) => (
              <li key={idx}>{c}</li>
            ))}
          </ul>
        </Section>
      )}
    </div>
  );
}

function Header({ data, isAr }: { data: CVData; isAr: boolean }) {
  const fullName = data.fullName || (isAr ? "الاسم الكامل" : "Full Name");
  const city = data.city || data.location || (isAr ? "المدينة" : "City");
  const phone = data.phone || (isAr ? "05xxxxxxxx" : "+966 5x xxx xxxx");
  const email = data.email || "name@email.com";
  const links = (data.links || []).filter(Boolean);

  return (
    <header className="cv-header">
      <div className="cv-name">{fullName}</div>
      {data.jobTitle && <div style={{ fontSize: '14px', fontWeight: 600, marginTop: '4px', opacity: 0.85 }}>{data.jobTitle}</div>}
      <div className="cv-contact">
        {joinMeta([city, phone, email, ...links], " | ")}
      </div>
    </header>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="cv-section">
      <h2 className="cv-h2">{title}</h2>
      <div className="cv-section-body">{children}</div>
    </section>
  );
}

function TwoColBlock({ templateId, children }: { templateId: string; children: React.ReactNode }) {
  const isTwoCol = templateId === "ats_ar_modern" || templateId === "ats_en_executive";
  return <div className={isTwoCol ? "cv-block cv-block-split" : "cv-block"}>{children}</div>;
}

function joinMeta(parts: (string | undefined)[], sep: string): string {
  return parts.filter(Boolean).join(sep);
}

function defaultSkills(isAr: boolean): string[] {
  return isAr
    ? ["التواصل", "حل المشكلات", "إدارة الوقت", "Excel", "PowerPoint", "العمل ضمن فريق"]
    : ["Communication", "Problem Solving", "Time Management", "Excel", "PowerPoint", "Teamwork"];
}

function defaultCerts(isAr: boolean): string[] {
  return isAr
    ? ["دورة في كتابة السيرة الذاتية", "شهادة إدارة مشاريع (اختياري)"]
    : ["Resume Writing Workshop", "Project Management Certificate (optional)"];
}
